# Generated by Django 4.2.7 on 2023-11-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height_image', upload_to='images/%Y/%m/%d/', width_field='width_image')),
                ('alternative', models.CharField(blank=True, max_length=50, null=True)),
                ('image_size', models.PositiveIntegerField(blank=True, null=True)),
                ('image_hash', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('width_image', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height_image', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
